<?php
session_start();
if(isset($_SESSION['joueur'])){
    require_once('jeux.php');
}elseif(isset($_SESSION['admin'])){
    require_once('admin.php');
}elseif(isset($_SESSION['signup'])){
    require_once('inscriptionJoueur.php');
}elseif(isset($_SESSION['idqst'])){
    require_once('jeux.php');
}else{
    require_once('connexion.php');
}
?>